### ISSUE TITLE
Reflection with Type and TypeInfo

### ISSUE THREAD

**Issue by theSoenke** [MarkerMetro/MarkerMetro.Unity.WinLegacy#12]
This plugin is really great when porting to WinRT, but i still have some problems with reflection in the System.Type class. When i use the ReflectionExtension class i currently have to edit a lot of the code to fix all errors on WinRT.  
It would be great if i could simply replace System.Type on WinRT with something like this: 

#if (UNITY_WINRT && UNITY_EDITOR)
using Type = MarkerMetro.Unity.WinLegacy.Reflection.ReflectionExtensions;
#endif

**Comment by keithpatton** [comment]
yes, in order to do this we would have had to completely re-implement the Type class. We chose instead to use an extensions approach because many of the implementations are static, however, what issues are you getting?

You should be able to do the following:

#if (UNITY_WINRT && !UNITY_EDITOR)
using  MarkerMetro.Unity.WinLegacy.Reflection.ReflectionExtensions;
#endif

Note that you should use a !UNITY_EDITOR to ensure that the code only compiles and runs on UNITY_WINRT.

If you have missing things withing ReflectionExtensions, feel free to add them and issue a PR so we can add?

Hope that helps.

**Comment by theSoenke** [comment]
I'm using a third party plugin and it uses reflection a lot. I can fix many errors with extension methods, but unfortunately c# does not support extension properties and so i have problems with BaseType or FieldHandle. Because of that i tried to implement the type class myself, but i failed ;)

**Comment by keithpatton** [comment]
yes, we chose to implement some of the properties as extension methods, so you do need to change the code in these areas to say IsValueType() rather than IsValueType and ifdef these areas. 

The Type class would be quite challenging to implement so we chose to do this although there is more of a footprint when porting.

**Comment by theSoenke** [comment]
This plugin really made porting a lot easier, but one problem i still have is the missing FieldHandle in FieldInfo. An extension method GetFieldHandle() in ReflexionExtension would be really helpful. I have currently no idea how i could get the RuntimeFieldHandle
